#if !canImport(ObjectiveC)
import XCTest

extension SimpleCowTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SimpleCowTests = [
        ("testCowInt", testCowInt),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(SimpleCowTests.__allTests__SimpleCowTests),
    ]
}
#endif
